sudo: required
services: 
  - docker 

before_install:
  - docker build -t blackjack1994/react-test -f ./client/Dockerfile.dev ./client 

script:
  - docker run blackjack1994/react-test npm run test -- --coverage

after_success:
  - docker build -t blackjack1994/multi-react ./client
  - docker build -t blackjack1994/multi-nginx ./nginx 
  - docker build -t blackjack1994/muti-server ./server
  - docker build -t blackjack1994/multi-worker ./worker
  # Log in docker hub
